# Generated by Django 5.2.7 on 2025-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user",
            new_name="username",
        ),
    ]
